// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_servers_host_ from "./routes/api/servers/[host].ts";
import * as $groups_name_ from "./routes/groups/[name].tsx";
import * as $groups_name_articles_id_ from "./routes/groups/[name]/articles/[id].tsx";
import * as $groups_name_articles_id_attachments_file_ from "./routes/groups/[name]/articles/[id]/attachments/[file].tsx";
import * as $groups_name_raw_id_ from "./routes/groups/[name]/raw/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $servers from "./routes/servers.tsx";
import * as $Groups from "./islands/Groups.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/servers/[host].ts": $api_servers_host_,
    "./routes/groups/[name].tsx": $groups_name_,
    "./routes/groups/[name]/articles/[id].tsx": $groups_name_articles_id_,
    "./routes/groups/[name]/articles/[id]/attachments/[file].tsx":
      $groups_name_articles_id_attachments_file_,
    "./routes/groups/[name]/raw/[id].tsx": $groups_name_raw_id_,
    "./routes/index.tsx": $index,
    "./routes/servers.tsx": $servers,
  },
  islands: {
    "./islands/Groups.tsx": $Groups,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
